[package]
edition = "2021"
name = "is20-token-canister"
version = "0.1.7"

[features]
default = []
no_api = []

[dependencies]
assert-panic = "1.0"
candid = "0.7"
ic-cdk = "0.5"
ic-cdk-macros = "0.5"
serde = "1.0"
ic-canister = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-canister", branch = "awkure/upgrade-fixes" }
ic-helpers = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-helpers", branch = "awkure/upgrade-fixes" }
ic-storage = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-storage", branch = "awkure/upgrade-fixes" }
# ic-helpers = { path = "../../../../ic-helpers/ic-helpers" }
# ic-storage = { path = "../../../../ic-helpers/ic-storage" }
# ic-canister = { path = "../../../../ic-helpers/ic-canister/ic-canister" }
ic-certified-map = "0.3"
token-api = { path = "../api", package = "is20-token" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
async-std = {version = "1.10.0", features = ["attributes"]}
