[package]
edition = "2021"
name = "is20-token-canister"
version = "0.2.0"

[features]
default = []
no_api = []

[dependencies]
assert-panic = "1.0"
candid = "0.7"
ic-cdk = "0.5"
ic-cdk-macros = "0.5"
serde = "1.0"
ic-canister = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-canister", tag = "v0.3.18" }
ic-helpers = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-helpers", tag = "v0.3.18" }
ic-storage = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-storage", tag = "v0.3.18" }
ic-auction = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-auction", tag = "v0.3.18" }
ic-certified-map = "0.3"
token-api = { path = "../api", package = "is20-token", features = ["auction", "claim"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
async-std = {version = "1.10.0", features = ["attributes"]}

[dev-dependencies]
tokio = { version = "1.20.1", features = ["rt", "macros"] }
coverage-helper = "0.1"
